# Generated by Django 5.0 on 2023-12-17 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=1200, null=True, verbose_name='title for seo')),
                ('seo_keyword', models.CharField(blank=True, max_length=1200, null=True, verbose_name='keyword for seo')),
                ('seo_alt', models.CharField(blank=True, max_length=1200, null=True)),
                ('seo_description', models.CharField(blank=True, max_length=1200, null=True, verbose_name='description for seo')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('content', models.TextField()),
                ('content_without_ck', models.CharField(max_length=200)),
                ('content_2', models.TextField()),
                ('content_without_ck_2', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=1200, null=True, verbose_name='title for seo')),
                ('seo_keyword', models.CharField(blank=True, max_length=1200, null=True, verbose_name='keyword for seo')),
                ('seo_alt', models.CharField(blank=True, max_length=1200, null=True)),
                ('seo_description', models.CharField(blank=True, max_length=1200, null=True, verbose_name='description for seo')),
                ('name', models.CharField(max_length=800)),
                ('description', models.TextField()),
                ('description_without_ck', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('bottomdescription', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Blog_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_images', to='mainapp.blog')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=1200, null=True, verbose_name='title for seo')),
                ('seo_keyword', models.CharField(blank=True, max_length=1200, null=True, verbose_name='keyword for seo')),
                ('seo_alt', models.CharField(blank=True, max_length=1200, null=True)),
                ('seo_description', models.CharField(blank=True, max_length=1200, null=True, verbose_name='description for seo')),
                ('name', models.CharField(max_length=800)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='mainapp.portfolio_category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
