# Generated by Django 5.0 on 2023-12-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='image',
            new_name='mainimage',
        ),
        migrations.AddField(
            model_name='blog',
            name='backimage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='in_home',
            field=models.BooleanField(default=False),
        ),
    ]
