# Generated by Django 5.0 on 2023-12-21 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_image_blog_mainimage_blog_backimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='categoy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.category'),
        ),
    ]
