# Generated by Django 5.0 on 2023-12-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_rename_categoy_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='second_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
