# Generated by Django 5.0 on 2024-01-06 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_remove_blog_tag_blog_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog_images',
        ),
    ]
